version: "3"

tasks:
  run:
    desc: Run the application
    deps:
      - generate
    env:
      LOG_LEVEL: debug
    cmds:
      - go run ./cmd/httb

  dev:
    desc: Run the application in development mode with auto-rebuild
    watch: true
    sources:
      - "**/*.go"
    env:
      LOG_LEVEL: debug
    cmds:
      - go run ./cmd/httb

  generate:
    desc: Generate code
    aliases: [gen]
    cmds:
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=.openapi/oapi-codegen.yml assets/openapi.yaml

  test:
    desc: Run all tests
    cmds:
      - go test ./...
  tdd:
    desc: Test Driven Development - Watch tests
    watch: true
    sources:
      - "**/*.go"
    cmds:
      - go test ./...

  lint:
    desc: Run all linters
    cmds:
      - go mod tidy
      - go run github.com/bombsimon/wsl/v4/cmd/wsl --allow-cuddle-declarations --force-err-cuddling --force-case-trailing-whitespace 3 --fix ./...
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run --fix
