version: "3"

tasks:
  generate:
    desc: Generate code
    aliases: [gen]
    cmds:
      - go generate ./...

  test:
    desc: Run all tests
    cmds:
      - go test ./...
  tdd:
    desc: Test Driven Development - Watch tests
    watch: true
    sources:
      - "**/*.go"
    cmds:
      - go test ./...

  lint:
    desc: Run all linters
    cmds:
      - go mod tidy
      - go run github.com/bombsimon/wsl/v4/cmd/wsl --allow-cuddle-declarations --force-err-cuddling --force-case-trailing-whitespace 3 --fix ./...
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint
