# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  build:
    desc: Build the application
    deps:
      - generate
    sources:
      - "**/*.go"
    generates:
      - .build/httb
    cmds:
      - go build -o .build/httb ./cmd/httb

  run:
    desc: Run the application
    deps:
      - build
    env:
      LOG_LEVEL: debug
    cmds:
      - .build/httb

  dev:
    desc: Run the application in development mode with auto-rebuild
    watch: true
    deps:
      - build
    env:
      LOG_LEVEL: debug
    cmds:
      - .build/httb

  generate:
    desc: Generate code
    aliases: [gen]
    sources:
      - assets/openapi.yaml
    generates:
      - internal/pkg/api/api.go
    cmds:
      - go run github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen --config=.openapi/oapi-codegen.yml assets/openapi.yaml

  test:
    desc: Run all tests
    cmds:
      - go test ./...
  tdd:
    desc: Test Driven Development - Watch tests
    watch: true
    sources:
      - "**/*.go"
    cmds:
      - go test ./...

  lint:
    desc: Run all linters
    cmds:
      - go mod tidy
      - go run github.com/bombsimon/wsl/v4/cmd/wsl --allow-cuddle-declarations --force-err-cuddling --force-case-trailing-whitespace 3 --fix ./...
      - go run github.com/golangci/golangci-lint/cmd/golangci-lint run --fix
